### PR TITLE
Model-Reference content for 1.17.0

### PR DESCRIPTION
**Pull request by Alberto-Villarreal**
# Description

> :memo: Update "Supported Configuration(s)" sections in README files to 1.17.0/2.3.1
>   
> * List any dependencies that are required for the changes.  

## Type of changes

Please specify the type of changes, and delete the options that are not relevant.

- [ X] Documentation update
- [ ] Bug fix (changes which fix an issue)
- [ ] Others (please specify)

## Tests

> :memo: Please describe the tests that you ran to verify your changes.
>  
> * Provide the instructions so that we can reproduce.  
> * Please also list any relevant details for your test configuration.  

## Checklist

- [X ] I agree with the [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] My code conforms to the following coding guidelines:
  - [ ] Use Python 3
  - [ ] Python code follows [PEP 8 Coding Styles](https://www.python.org/dev/peps/pep-0008/)
- [ ] I have performed a self code review.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Alberto-Villarreal** [comment]
Please review, Thanks

**Comment by Alberto-Villarreal** [comment]
Please review changes, thanks

**Review by mandy-li — CHANGES_REQUESTED** [review]
Reject the PR. you should submit patch to internal gerrit.

**Comment by Alberto-Villarreal** [comment]
Closing. Changes will be submitted in Gerrit.

**Pull request closed without merging**
